name: meuplanoai

services:
  # Backend em desenvolvimento
  backend-dev:
    container_name: backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    env_file:
      - ./backend/.env.development
    depends_on:
      - mongodb  # Depende do MongoDB

  # Backend para testes
  backend-test:
    container_name: backend-test
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: test
    env_file:
      - ./backend/.env.development
    depends_on:
      - mongodb

  # Frontend em desenvolvimento
  frontend-dev:
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - FRONTEND_PORT=5173
    env_file:
      - ./frontend/.env.development

  # Frontend para testes
  frontend-test:
    container_name: frontend-test
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: test
    env_file:
      - ./frontend/.env.development

  # MONGODB - Banco de dados
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:  # Volume para guardar os dados do MongoDB